# TOKEN 
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZV9pZCI6MiwiaWF0IjoxNzAwNDg4ODQyLCJleHAiOjE3MDA0OTA2NDJ9.nSekZ72lr5NIkRRM2RTrza3H2gDGO1s6zq3kXIVuRQ8



# GET ALL POKEMONS INFORMATIONS
GET http://localhost:3000/pokemon

###

# GET A POKEMONS INFORMATION
GET http://localhost:3000/pokemon/150

###

GET http://localhost:3000/type

###

# ACCOUNT CREATION
POST http://localhost:3000/sign-up
Content-Type: application/json

{
    "pseudo": "Charlatan",
    "email":"antho.mirland@gmail.com",
    "password":"Azerty123!",
    "confirmpassword": "Azerty123!"
}

###

# USER LOGIN
POST http://localhost:3000/sign-in
Content-Type: application/json

{
    "email":"antho.mirland@gmail.com",
    "password":"Azerty123!"
}

###


# ADDING A POKEMON IN USER'S COLLECTION
POST http://localhost:3000/me/collection
Content-Type: application/json
Authorization: {{token}}

{
    "pokemonId":1
}