# TOKEN 
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZV9pZCI6MiwiaWF0IjoxNzAwNDkxOTIyLCJleHAiOjE3MDA0OTM3MjJ9.5A3mLrrJzh6SvR_mMtvgng1kh-oV4F7kSKxelTdpZks



# GET ALL POKEMONS INFORMATIONS
GET http://localhost:3000/pokemon

###

# GET A POKEMONS INFORMATION
GET http://localhost:3000/pokemon/150

###

GET http://localhost:3000/type

###

# ACCOUNT CREATION
POST http://localhost:3000/sign-up
Content-Type: application/json

{
    "pseudo": "Charlatan",
    "email":"antho.mirland@gmail.com",
    "password":"Azerty123!",
    "confirmpassword": "Azerty123!"
}

###

# USER LOGIN
POST http://localhost:3000/sign-in
Content-Type: application/json

{
    "email":"antho.mirland@gmail.com",
    "password":"Azerty123!"
}

###


# GETTING ALL POKEMONS IN USER'S COLLECTION
GET  http://localhost:3000/me/collection
Content-Type: application/json
Authorization: {{token}}

###


# ADDING A POKEMON IN USER'S COLLECTION
POST http://localhost:3000/me/collection
Content-Type: application/json
Authorization: {{token}}

{
    "pokemonId":1
}


###

# DELETING A POKEMON IN USER'S COLLECTION
DELETE  http://localhost:3000/me/collection/150
Content-Type: application/json
Authorization: {{token}}
