# GET ALL POKEMONS INFORMATIONS
GET http://localhost:3000/pokemon

###

# GET A POKEMONS INFORMATION
GET http://localhost:3000/pokemon/150

###

GET http://localhost:3000/type

###

# ACCOUNT CREATION
POST http://localhost:3000/sign-up
Content-Type: application/json

{
    "pseudo": "Charlatan",
    "email":"antho.mirland@gmail.com",
    "password":"Azerty123!",
    "confirmpassword": "Azerty123!"
}

###

# USER LOGIN
POST http://localhost:3000/sign-in
Content-Type: application/json

{
    "email":"antho.mirland@gmail.com",
    "password":"Azerty123!"
}